### ISSUE TITLE
SikuliX project in IntelliJ IDEA 14.02 - correct settings?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration#4]
This pictures show how I configured IntelliJ IDEA to work with SikuliX. Please check if I did everything right.

![Global-SDKs](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_00_Global-SDKs.png)

![Project-SDKs](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_01_Project-SDK.png)

![Modules Sources](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_02_Modules_Sources.png)

![Modules Paths](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_03_Modules_Paths.png)

![Modules Dependencies](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_04_Modules_Dependencies.png)

![Libraries](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_05_Libraries.png)

![Libraries 2](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Setup_Project-Structure_05_Libraries_2.png)

And this is how the project structure looks like with the above settings:

![IDE Project Structure](https://raw.githubusercontent.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration/Windows-8.1/documentation/images/JI-14.02_CE-IDE_Project-Structure.png)

**Comment by RaiMan** [comment]
I have no experiences with IntelliJ at all and I will never use it due to their license policy (the community edition only supports Java 6 - a shame).
For Java development I use NetBeans and for specific Python/Jython situations, I have Eclipse PyDev.

**Comment by Tset-Noitamotua** [comment]
Somewhere I have read that NetBeans dropped Jython support. My experiments with the recent Python plugin weren´t successfull, too. So I gave up NetBeans - maybe I give it a try sometime later. And Eclipse I just can´t stand - maybe because my job is testing Eclipse based application the whole day ;-))). IntelliJ is the best I have for now although I´m not very happy with it, too.

The summary of that misery is the reason for [my question on stackoverflow](http://stackoverflow.com/questions/27924485/is-there-any-way-to-get-jython-support-in-vim-gvim) ;-)))))

**Comment by RaiMan** [comment]
For Netbeans (I am now on 7.4 and 8) the Python plugin available with version 6.9 is no longer/not yet officially available. But at least for 7.4 there is somewhere in the net a version, that can be used.
… but I do not have it.
For my Java development I am completely satisfied with Netbeans.
For some Python/Jython evaluations and tests, Eclipse Luna with PyDev on my Windows 8 does what I need.

BTW: Since with the final 1.1.0 it is possible, to on the fly add stuff to Java classpath and from the Java level control the Jython sys.path, I think I will add some basic support, that allows to run a RFW test from within a SikuliX script (from IDE or command line).
In version 2 it will be possible to edit RFW tests (at least text files) in the table view and run them.
So it would be possible to work on tests and libraries in parallel.
